rabbitmq:
  amp:
    username: YOUR_AMP_USERNAME
    password: YOUR_AMP_PASSWORD
    host: YOUR_AMP_HOST
    port: YOUR_AMP_PORT
    queue: YOUR_QUEUE
    virtualhost: YOUR_VIRTUAL_HOST
    exchange: MY_EXCHANGE
    routingkey: "MY_ROUTING_KEY"
