name: count dependencies

on:
  push:
  workflow_dispatch: {}

jobs:
  linux-count-dependecies:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./apache-beam-dependency-problem

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'liberica'
      - run: ./gradlew clean installDist

      - name: count dependencies
        run: ls build/install/apache-beam-dependency-problem/lib/ | wc -l

  mac-count-dependecies:
    runs-on: macos-latest

    defaults:
      run:
        working-directory: ./apache-beam-dependency-problem

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'liberica'
      - run: ./gradlew clean installDist

      - name: count dependencies
        run: ls build/install/apache-beam-dependency-problem/lib/ | wc -l
