name: count dependencies

on:
  push:
  workflow_dispatch: {}

jobs:
  pure-java-linux-count-dependecies:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./apache-beam-dependency-problem
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'liberica'
      - run: ./gradlew clean installDist
      - name: show dependencies
        run: ls -lah  build/install/apache-beam-dependency-problem/lib
      - name: count dependencies
        run: ls build/install/apache-beam-dependency-problem/lib/ | wc -l

  skdman-java-linux-count-dependecies:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./apache-beam-dependency-problem
    steps:
      - uses: actions/checkout@v4
      - name: ls
        run: ls -lah
      - run: echo $JAVA_HOME
      - uses: sdkman/sdkman-action@main
        id: sdkman
        with:
          candidate: java
          version: 21.0.1-librca
      - run: java -version
      - run: echo $JAVA_HOME
      - run: ls -lah ~/.sdkman/candidates/java/
      - run: echo 'export JAVA_HOME=~/.sdkman/candidates/java/current' >> ~/.bash_profile
      - run: echo 'export PATH=${PATH}:${JAVA_HOME}/bin' >> ~/.bash_profile
      - run: cat ~/.bash_profile
      - run: source ~/.bash_profile
      - run: echo $JAVA_HOME
      - run: ./gradlew clean installDist
      - name: show dependencies
        run: ls -lah  build/install/apache-beam-dependency-problem/lib
      - name: count dependencies
        run: ls build/install/apache-beam-dependency-problem/lib/ | wc -l

  mac-count-dependecies:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: ./apache-beam-dependency-problem
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'liberica'
      - run: ./gradlew clean installDist
      - name: show dependencies
        run: ls -lah  build/install/apache-beam-dependency-problem/lib
      - name: count dependencies
        run: ls build/install/apache-beam-dependency-problem/lib/ | wc -l
