name: Macos tryout
on:
  push:
    branches: [ mac ]
  workflow_dispatch: {}

jobs:
    mac:
        runs-on: macos-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Install OrbStack
              run: |
                  echo "Installing OrbStack"
                  brew install orbstack
                  echo "Adding OrbStack to PATH"
                  export PATH="$HOME/.orbstack/bin:$PATH"
                  echo "Starting OrbStack"
                  orb start &
                  echo "OrbStack started"
                  orb status
                  if [ -f ~/.orbstack/logs/orbstack.log ]; then
                    cat ~/.orbstack/logs/orbstack.log
                  else
                    echo "Log file not found in ~/.orbstack/logs/"
                  fi


          
