name: Macos tryout
on:
  push:
    branches: [ mac ]
  workflow_dispatch: {}

jobs:
  mac:
    runs-on: macos-13
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install OrbStack
        run: |
          curl -fsSL https://orbstack.dev/install.sh | sh
          orb start &
          echo "OrbStack started"
      - name: logs
        run: cat ~/.orbstack/logs/orbstack.log

      - name: Check Docker version
        run: docker --version





          
