name: Macos tryout
on:
  push:
    branches: [ mac ]
  workflow_dispatch: {}

jobs:

    mac-colima:
      runs-on: macos-14
      steps:
        - uses: actions/checkout@v4
        - name: Install colima
          run: |
            brew install colima 
            brew install --cask docker
            # brew services start colima
            # colima delete
            colima start --cpu 4 --memory 8GiB
            # sudo ln -s ~/Library/Containers/com.docker.docker/Data/docker.raw.sock /var/run/docker.sock

            # DOCKER_HOST=unix://$HOME/.colima/docker.sock 



            # ls -lah /var/run

            # export DOCKER_HOST="unix://$HOME/.colima/docker.sock"
            echo "before d ps"
            docker ps # test that it works using linked socket file

            # sudo ln -s $HOME/.colima/docker.sock /var/run/docker.sock
            sudo docker info
            sudo docker run hello-world
