name: Macos tryout
on:
  push:
    branches: [ mac ]
  workflow_dispatch: {}

jobs:
  mac:
    runs-on: macos-latest
    steps:
      - name: Install OrbStack
        run: brew install --cask orbstack

      - name: Open OrbStack
        run: open -a /Applications/OrbStack.app

      - name: Wait for OrbStack to Start
        run: sleep 10

      - name: ls
        run: |
          ls -l /opt//
          echo "*********"
          ls -l /opt/homebrew/
          echo "*********"
          ls -l /opt/homebrew/bin/
      - name: Add OrbStack Docker to PATH
        run: | 
          echo "/opt/orbstack/bin" >> $GITHUB_PATH
          echo "/opt/homebrew/bin" >> $GITHUB_PATH
          


      - name: Verify Docker Installation
        run: docker --version

#      - name: Add OrbStack Docker to PATH
#        run: |
#          echo "/opt/orbstack/bin" >> $GITHUB_PATH
#
#      - name: Verify Docker Installation
#        run: docker --version
#          docker
          
