name: Macos tryout
on:
  push:
    branches: [ mac ]
  workflow_dispatch: {}

jobs:
    mac:
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v4
            - name: Install OrbStack
              run: |
                  echo "Installing OrbStack"
                  brew install --cask orbstack
                  echo "Adding OrbStack to PATH"
                  export PATH="$HOME/.orbstack/bin:$PATH"
                  echo "Starting OrbStack"
                  echo "OrbStack started"
                  echo "before orb status"
                  orb status
                  echo "after orb status"
                  orb report
                  

          
