name: Macos tryout
on:
  push:
    branches: [ mac ]
  workflow_dispatch: {}

jobs:

    mac-action:
      runs-on: macos-13
        - name: Setup Docker on macOs
          uses: douglascamata/setup-docker-macos-action@v1-alpha
        - name: docker ps
          run: |
            docker ps


    mac-colima:
      runs-on: macos-14
      steps:
        - uses: actions/checkout@v4
        - name: Install colima
          run: |
            brew update
            brew install colima 
            brew install qemu
            brew install --cask docker
            # brew services start colima
            colima delete -f || true
            colima start --cpu 4 --memory 8  --vz-rosetta    

            echo "Waiting for Colima to start..."
            sleep 120  # Increase sleep time

            # Verify Colima status
            while ! colima status | grep -q 'Running'; do
              echo "Waiting for Colima to be fully up..."
              sleep 10
            done
            
            # Verify Colima status
            colima status
            
            # Dynamically extract the SSH port from Colima's status
            SSH_PORT=$(colima status | grep -oP '(?<=SSH Local Port: )\d+')

            echo "Colima is using SSH port $SSH_PORT"

            # Check if the extracted port is open
            echo "Checking if port $SSH_PORT is open..."
            nc -zv 127.0.0.1 $SSH_PORT
            
            # sudo ln -s ~/Library/Containers/com.docker.docker/Data/docker.raw.sock /var/run/docker.sock

            # DOCKER_HOST=unix://$HOME/.colima/docker.sock 



            # ls -lah /var/run

            # export DOCKER_HOST="unix://$HOME/.colima/docker.sock"
            echo "before d ps"
            docker ps # test that it works using linked socket file

            # sudo ln -s $HOME/.colima/docker.sock /var/run/docker.sock
            sudo docker info
            sudo docker run hello-world
        - name: Output Colima logs
          if: failure()
          run: cat /Users/runner/.colima/_lima/colima/ha.stderr.log
