name: Macos tryout
on:
  push:
    branches: [ mac ]
  workflow_dispatch: {}

jobs:
  mac:
    runs-on: macos-13
    steps:
#      - name: Install QEMU
#        run: brew install qemu
#
#      - name: Locate QEMU
#        run: which qemu-system-aarch64
#
#      - name: Verify QEMU Installation
#        run: qemu-system-aarch64 --version
#
#      - name: Add QEMU to PATH
#        run: echo "/opt/homebrew/bin" >> $GITHUB_PATH
#
#      - name: Verify QEMU Installation
#        run: qemu-system-aarch64 --version
#
#      - name: Install Colima and Docker
#        run: brew install colima docker
#
#      - name: Update Colima
#        run: brew upgrade colima
#
#      - name: Show Colima Logs
#        run: |
#          cat /Users/runner/.colima/_lima/colima/ha.stderr.log || true
#          cat /Users/runner/.colima/_lima/colima/serial*.log || true
#
#      - name: Restart and Start Colima
#        run: |
#          colima stop || true
#          colima delete || true
#          colima start

#      - name: install docker
#        run: |
#          brew install --cask docker
#          sudo /Applications/Docker.app/Contents/MacOS/Docker --unattended --install-privileged-components
#          open -a /Applications/Docker.app --args --unattended --accept-license
#          docker --version
      - name: install docker
        run: |
          brew install docker colima
              colima start
              echo "Waiting for SSH to be available..."
              for i in {1..60}; do
                if ssh -o ConnectTimeout=2 -p 49204 127.0.0.1 exit; then
                  break
                fi
                sleep 2
              done
    
          docker --version
          
          
