name: Macos tryout
on:
  push:
    branches: [ mac ]
  workflow_dispatch: {}

jobs:
  mac:
    runs-on: macos-latest
    steps:
      - name: Install Colima and Docker
        run: |
          brew install colima docker

      - name: Start Colima
        run: colima start

      - name: Add Docker to PATH
        run: echo "/opt/homebrew/bin" >> $GITHUB_PATH

      - name: Verify Docker Installation
        run: docker --version
          
