name: Macos tryout
on:
  push:
    branches: [ mac ]
  workflow_dispatch: {}

jobs:
  mac:
    runs-on: macos-latest
    steps:
      - name: Verify QEMU Installation
        run: qemu-system-aarch64 --version

      - name: Install Colima and Docker
        run: brew install colima docker

      - name: Update Colima
        run: brew upgrade colima

      - name: Show Colima Logs
        run: |
          cat /Users/runner/.colima/_lima/colima/ha.stderr.log || true
          cat /Users/runner/.colima/_lima/colima/serial*.log || true

      - name: Restart and Start Colima
        run: |
          colima stop || true
          colima delete || true
          colima start

      - name: Verify Docker Installation
        run: docker --version
