name: Macos tryout
on:
  push:
    branches: [ mac ]
  workflow_dispatch: {}

jobs:
  mac:
    runs-on: macos-13
    steps:
      - name: Set up Docker
        uses: appleboy/setup-docker@v1
      - name: Check Docker version
        run: docker --version




          
